version: '3'
services:
    plantas:
        build:
            context: .
            dockerfile: Dockerfile
        image: plantas-image
        container_name: plantas-container
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - plantas-network
    plantas-webserver:
        image: nginx:stable-alpine3.20
        container_name: plantas-nginx-webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - plantas-network
    plantas-mysql:
        image: mysql:8.0.32
        container_name: plantas-mysql-db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=plantas
            - MYSQL_USER=root
networks:
    plantas-network:
