version: '3'
services:
  plantas:
    image: jonaykb/plantas-image
    container_name: plantas-container
    restart: unless-stopped
    depends_on:
      - plantas-mysqldb
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    command: >
      sh -c "
      composer update &&
      composer install &&
      php artisan migrate &&
      php artisan migrate --database=sqliteLocal &&
      php-fpm
      "
    networks:
      - plantas-network



  plantas-webserver:
    image: jonaykb/plantas-nginx-webserver-image
    container_name: plantas-nginx-webserver
    restart: unless-stopped
    depends_on:
      - plantas
    ports:
      - "8080:80"
#    volumes:
#     - .:/var/www
#      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - plantas-network

  plantas-mysqldb:
    image: mysql:8.3.0
    container_name: plantas-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
#    ports:
#      - "3306:3306"
    volumes:
      - plantas-dbdata
      - ./docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - plantas-network

volumes:
  plantas-dbdata:
networks:
  plantas-network:
